
addons:
  postgresql: "9.1"

env:
  global:
    - SQLALCHEMY_DATABASE_URI="postgresql://postgres@127.0.0.1:travis_ci_test"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

language: python

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: "python manage.py -c ../config/travis.cfg testall"
