language: python

sudo: false

python:
  - "2.7"
  - "3.7"

# Match postgresql version to that in conf/pillar/project.sls
addons:
  postgresql: "9.3"

# We have to use ../config since Flask files are relative to the *app* not the project
env:
  - FLASK_APPLICATION_SETTINGS="../config/travis.cfg"

before_script:
  - psql -c "create database travis_ci_test;" -U postgres

# command to install dependencies
install:
  - "pip install -r config/dev.reqs.txt"

# command to run tests
script:
  - "python manage.py testall"

notifications:
  email: false
