
addons:
  postgresql: "9.1"

env:
  global:
    - FLASK_APPLICATION_SETTINGS="../config/travis.cfg"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

language: python

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: "python manage.py testall"

notifications:
  email: false
